"""Generate a new Windows Production reference without overwriting prior evidence."""

from __future__ import annotations

import argparse
import json
import platform
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from dps_studio.release.portable_reference import (  # noqa: E402
    capture_snapshot, file_hash, lf_text_hash, reference_environment,
)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--export-root", type=Path, required=True)
    args = parser.parse_args()
    if platform.system() != "Windows":
        raise RuntimeError("The reference must be generated by Windows Production")
    if args.output.exists() or args.export_root.exists():
        raise FileExistsError("Reference and export destinations must be new")
    snapshot = capture_snapshot(ROOT / "docs" / "原始数据.csv", args.export_root)
    reference = {
        "generator": "tools/generate_macos_portable_reference.py",
        "production_commit": subprocess.check_output(
            ["git", "rev-parse", "HEAD"], cwd=ROOT, text=True,
        ).strip(),
        "environment": reference_environment(),
        "scientific_source_sha256_lf": {
            path.relative_to(ROOT).as_posix(): lf_text_hash(path)
            for path in sorted((ROOT / "src" / "dps_studio" / "core").rglob("*.py"))
        },
        "snapshot": snapshot,
    }
    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("x", encoding="utf-8", newline="\n") as handle:
        json.dump(reference, handle, ensure_ascii=False, allow_nan=False, separators=(",", ":"))
        handle.write("\n")
    print(f"Windows reference: {args.output}; SHA-256={file_hash(args.output)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
